package casbin_enforcers

import "testing"

func TestDummy(t *testing.T) {
	d := &DummyEnforcer{}
	var sa []string
	var saa [][]string
	var ok bool
	err := ErrorUnsupported
	checkReturns := func() {
		if sa != nil || saa != nil || ok {
			t.Fatal("One or more return values not nil for dummy class")
		}
		if err != ErrorUnsupported {
			t.Fatal("Unexpected error condition returned")
		}
	}
	sa, err = d.GetRolesForUser("")
	checkReturns()
	sa, err = d.GetUsersForRole("")
	checkReturns()
	ok, err = d.HasRoleForUser("", "")
	checkReturns()
	ok, err = d.AddRoleForUser("", "")
	checkReturns()
	ok, err = d.DeleteRoleForUser("", "")
	checkReturns()
	ok, err = d.DeleteRolesForUser("")
	checkReturns()
	ok, err = d.DeleteUser("")
	checkReturns()
	ok, err = d.DeleteRole("")
	checkReturns()
	ok, err = d.DeletePermission("")
	checkReturns()
	ok, err = d.AddPermissionForUser("", "")
	checkReturns()
	ok, err = d.DeletePermissionForUser("", "")
	checkReturns()
	ok, err = d.DeletePermissionsForUser("")
	checkReturns()
	saa, err = d.GetPermissionsForUser("")
	checkReturns()
	ok, err = d.HasPermissionForUser("", "")
	checkReturns()
	sa, err = d.GetImplicitRolesForUser("", "")
	checkReturns()
	saa, err = d.GetImplicitPermissionsForUser("", "")
	checkReturns()
	sa, err = d.GetImplicitUsersForPermission("")
	checkReturns()
	sa = d.GetUsersForRoleInDomain("", "")
	checkReturns()
	sa = d.GetRolesForUserInDomain("", "")
	checkReturns()
	saa = d.GetPermissionsForUserInDomain("", "")
	checkReturns()
	ok, err = d.AddRoleForUserInDomain("", "", "")
	checkReturns()
	ok, err = d.DeleteRoleForUserInDomain("", "", "")
	checkReturns()
	sa, err = d.GetAllSubjects()
	checkReturns()
	sa, err = d.GetAllNamedSubjects("")
	checkReturns()
	sa, err = d.GetAllObjects()
	checkReturns()
	sa, err = d.GetAllNamedObjects("")
	checkReturns()
	sa, err = d.GetAllActions()
	checkReturns()
	sa, err = d.GetAllNamedActions("")
	checkReturns()
	sa, err = d.GetAllRoles()
	checkReturns()
	sa, err = d.GetAllNamedRoles("")
	checkReturns()
	saa, err = d.GetPolicy()
	checkReturns()
	saa, err = d.GetFilteredPolicy(0, "")
	checkReturns()
	saa, err = d.GetNamedPolicy("")
	checkReturns()
	saa, err = d.GetFilteredNamedPolicy("", 0, "")
	checkReturns()
	saa, err = d.GetGroupingPolicy()
	checkReturns()
	saa, err = d.GetFilteredGroupingPolicy(0, "")
	checkReturns()
	saa, err = d.GetNamedGroupingPolicy("")
	checkReturns()
	saa, err = d.GetFilteredNamedGroupingPolicy("", 0, "")
	checkReturns()
	ok, err = d.HasPolicy("")
	checkReturns()
	ok, err = d.HasNamedPolicy("", "")
	checkReturns()
	ok, err = d.AddPolicy("")
	checkReturns()
	ok, err = d.AddNamedPolicy("", "")
	checkReturns()
	ok, err = d.RemovePolicy("")
	checkReturns()
	ok, err = d.RemoveFilteredPolicy(0, "")
	checkReturns()
	ok, err = d.RemoveNamedPolicy("", "")
	checkReturns()
	ok, err = d.RemoveFilteredNamedPolicy("", 0, "")
	checkReturns()
	ok, err = d.HasGroupingPolicy("")
	checkReturns()
	ok, err = d.HasNamedGroupingPolicy("", "")
	checkReturns()
	ok, err = d.AddGroupingPolicy("")
	checkReturns()
	ok, err = d.AddNamedGroupingPolicy("", "")
	checkReturns()
	ok, err = d.RemoveGroupingPolicy("")
	checkReturns()
	ok, err = d.RemoveFilteredGroupingPolicy(0, "")
	checkReturns()
	ok, err = d.RemoveNamedGroupingPolicy("", "")
	checkReturns()
	ok, err = d.RemoveFilteredNamedGroupingPolicy("", 0, "")
	checkReturns()
	d.AddFunction("", nil)

}
